# Generated by Django 4.1.3 on 2022-11-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_alter_doctorprofile_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('D', 'Dermatology'), ('FM', 'Family_Medicine'), ('IM', 'Internal_Medicine'), ('N', 'Neurosurgery'), ('G', 'Gynaecology'), ('O', 'Oncology'), ('PA', 'Paediatrics'), ('PS', 'Psychiatry'), ('U', 'Urology'), ('PH', 'Public_Health')], max_length=2, null=True),
        ),
    ]
