# Generated by Django 4.1.3 on 2022-11-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_alter_doctorprofile_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='county',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('MOMBASA', 'Mombasa')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('Dermatology', 'Dermatology'), ('Family Medicine', 'Family Medicine'), ('Internal Medicine', 'Internal Medicine'), ('Neurosurgery', 'Neurosurgery'), ('Gynaecology', 'Gynaecology'), ('Oncology', 'Oncology'), ('Paediatrics', 'Paediatrics'), ('Psychiatry', 'Psychiatry'), ('Urology', 'Urology'), ('Public Health', 'Public Health')], max_length=50, null=True),
        ),
    ]
