# Generated by Django 4.1.3 on 2022-11-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_alter_doctorprofile_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='county',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa')], max_length=255, null=True),
        ),
    ]
