# Generated by Django 4.1.3 on 2022-11-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0007_alter_appointment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appontment_date',
            field=models.DateField(null=True),
        ),
    ]
