# Generated by Django 4.1.3 on 2022-11-11 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0009_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='county',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthcare.region'),
            preserve_default=False,
        ),
    ]
