# Generated by Django 4.1.3 on 2022-11-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0010_alter_doctorprofile_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='county',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
