# Generated by Django 4.1.3 on 2022-11-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0013_alter_appointment_doctor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='user_id',
            new_name='user',
        ),
    ]
