# Generated by Django 4.1.3 on 2022-11-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0020_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='has_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
