# Generated by Django 4.1.3 on 2022-11-18 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthcare', '0021_doctorprofile_has_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('Dermatology', 'Dermatology'), ('Family Medicine', 'Family Medicine'), ('Internal Medicine', 'Internal Medicine'), ('Neurosurgery', 'Neurosurgery'), ('Gynaecology', 'Gynaecology'), ('Oncology', 'Oncology'), ('Paediatrics', 'Paediatrics'), ('Psychiatry', 'Psychiatry'), ('Urology', 'Urology'), ('Public Health', 'Public Health')], max_length=50)),
                ('biography', models.TextField(default='-', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
